[package]
name = "sudoaudit"
version = "0.1.0"
edition = "2024"

[dependencies]
rip = { git = "https://github.com/prefix-dev/rip.git", package = "rip" }
tokio = { version = "1.0", features = ["full"] }
